using System;
using System.Collections.Generic;

namespace FeatureGraph
{
	public class FeatureExecutionBatch
	{
		private Dictionary<string, Feature> _generators = new();

		public List<Feature> batch { get; private set; } = new();

		public FeatureExecutionBatch(ICollection<Feature> features)
		{
			// Build a dictionary of the features that generate each of the non-user data blocks
			foreach (Feature feature in features)
			{
				List<Feature.ParameterMetaData> meta = feature.BuildMetaData();
				foreach (Feature.ParameterMetaData data in meta)
				{
					if (data.output)
					{
						if(data.reference!=null)
							_generators[data.reference.blockname] = feature;
						else
						{
							foreach (var obj in data.list)
								_generators[((IDataRef)obj).blockname] = feature;
						}
					}
				}
			}

			// Create an execution batch by backtracking from the inputs of enabled features 
			foreach (Feature feature in features)
			{
				if(feature.enabled)
					Include(feature);
			}
		}

		private bool Include(Feature feature)
		{
			if (batch.Contains(feature))
				return true;
			
			List<Feature.ParameterMetaData> meta = feature.BuildMetaData();

			bool skipRebuild = false;
			bool needsRebuild = false;
			int i = 1;
			foreach (Feature.ParameterMetaData data in meta)
			{
				if (data.output)
				{
					// For outputs, we will rebuild only if it does not exist.
					if (data.reference != null)
					{
						feature.SetParameter(i++, data.reference);
						needsRebuild |= !data.reference.hasData;
					}
					else
					{
						feature.SetParameter(i++, data.list);
						foreach(var obj in data.list)
							needsRebuild |= !((IDataRef) obj).hasData;
					}
				}
				else
				{
					// For inputs, we'll check if it's generated by another feature, and if so, check if that feature needs to be rebuilt first.
					// If it does, we won't rebuild "this" feature since it has to wait for the prior data to be updated
					// If it does not, we'll rebuild this if any input changed
					if (data.reference != null)
					{
						if(_generators.TryGetValue(data.reference.blockname, out Feature dependency))
							skipRebuild |= Include(dependency);

						needsRebuild |= data.reference.changed;
						feature.SetParameter(i++, data.reference.data);
					}
					else if (data.list != null)
					{
						foreach(var obj in data.list)
						{
							if(_generators.TryGetValue(((IDataRef)obj).blockname, out Feature dependency))
								skipRebuild |= Include(dependency);
							needsRebuild |= ((IDataRef)obj).changed;
						}
						
						if(data.listAsArray.Length!=data.list.Count)
							data.listAsArray = Array.CreateInstance(data.listElementType, data.list.Count);
						for(int x=0;x<data.listAsArray.Length;x++)
							data.listAsArray.SetValue(((IDataRef)data.list[x]).data,x); 

						feature.SetParameter(i++, data.listAsArray);
					}
				}
			}

			feature.SetParameter(0, FeatureManager.transientChange);

			if (needsRebuild && !skipRebuild)
			{
				batch.Add(feature);
			}
			
			return needsRebuild;
		}
	}
}